name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        ports:
          - 5432:5432

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rocketpay_test

    steps:
    - uses: actions/checkout@v2

    - name: Setup Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.4'
        otp-version: '22.2.1'

    - name: Install dependencies
      run: mix deps.get

    - name: Run tests
      run: mix test
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: $❴❴ job.services.postgres.ports[5432] ❵❵

    - name: Check code qualit
      run: mix format --check-formatted && mix credo --strict